# Generated by Django 4.2.1 on 2023-06-16 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='propic',
            field=models.ImageField(blank=True, max_length=255, upload_to='pictures/'),
        ),
    ]
